//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shiaDBEntities : DbContext
    {
        public shiaDBEntities()
            : base("name=shiaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationAcceptance> ApplicationAcceptance { get; set; }
        public virtual DbSet<EquipmentBreakdown> EquipmentBreakdown { get; set; }
        public virtual DbSet<EquipmentCard> EquipmentCard { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<OrganizationEmployee> OrganizationEmployee { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<StatusOfApplicationAcceptance> StatusOfApplicationAcceptance { get; set; }
        public virtual DbSet<StatusOfEquipment> StatusOfEquipment { get; set; }
        public virtual DbSet<StatusOfOrganiztionEmployee> StatusOfOrganiztionEmployee { get; set; }
        public virtual DbSet<StatusOfRepair> StatusOfRepair { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfEquipment> TypeOfEquipment { get; set; }
    }
}
